name: 'Setup massdns'
runs:
  using: "composite"
  steps:
    - run: |
        sudo git clone https://github.com/blechschmidt/massdns.git /usr/local/src/massdns
        cd /usr/local/src/massdns
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          sudo make
        else
          sudo make nolinux
        fi
        sudo make install
      shell: bash
