name: Release

on:
  release:
    types:
      - created

jobs:
  lint_and_test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Lint
        run: |
          go install golang.org/x/lint/golint@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          make lint

      - name: Setup massdns
        uses: ./.github/actions/setup-massdns

      - name: Test
        run: make test

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: amd64
          - os: ubuntu-latest
            platform: arm64
          - os: macos-latest
            platform: amd64
          - os: macos-latest
            platform: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build
        env:
          CGO_ENABLED: 0
          GOARCH: ${{ matrix.platform }}
        run: |
          make
          tar czf puredns-${{ runner.os }}-${{ matrix.platform }}.tgz puredns

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: puredns-${{ runner.os }}-${{ matrix.platform }}.tgz

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/puredns-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
